<?php
/**
 * File Name: Create.php
 * Automatically generated by QHGC tool
 * @date: 2021-05-25 16:49:27
 * @version: 4.0.4
 */

namespace qh4module\rabc_adv\models\depart;


use qh4module\rabc_adv\HpRabcAdv;
use qttx\helper\ArrayHelper;
use qh4module\token\TokenFilter;
use QTTX;

/**
 * Class Create
 * tbl_bk_depart表新增一条数据
 * @package backend\models\models\rabc
 */
class Create extends DepartModel
{

    /**
     * @var string 接收参数,必须：部门名称
     */
    public $name;

    /**
     * @var string 接收参数,非必须：说明
     */
    public $desc;

    /**
     * @var int 接收参数,排序
     */
    public $sort = 0;

    /**
     * @var array 接收参数,上级id
     */
    public $parent_ids;


    /**
     * @inheritDoc
     */
    public function rules()
    {
        return ArrayHelper::merge([
            [['name'], 'required'],
            [['parent_ids'], 'array', 'type' => 'string'],
            [['parent_ids'],'parentRule'],
        ], parent::rules());
    }


    public function parentRule()
    {
        // 检查多个部门的从属关系
        foreach ($this->parent_ids as $pid) {
            $children = HpRabcAdv::getDepartAllChildren($pid, $this->external);
            foreach ($this->parent_ids as $pid2) {
                if (in_array($pid2, $children)) {
                    return '多个上级部门之间不能存在从属关系';
                }
            }
        }
        return true;
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        $db = $this->external->getDb();

        $db->beginTrans();

        try {

            $id = QTTX::$app->snowflake->id();
            $db->insert($this->external->departTableName())
                ->cols([
                    'id' => $id,
                    'name' => $this->name,
                    'create_by' => TokenFilter::getPayload('user_id'),
                    'create_time' => time(),
                    'desc' => $this->desc,
                    'sort' => $this->sort,
                    'del_time' => 0
                ])
                ->query();

            if (empty($this->parent_ids)) {
                $this->parent_ids = [''];
            }
            foreach ($this->parent_ids as $pid) {
                $db->insert($this->external->departRelationTableName())
                    ->cols([
                        'id' => QTTX::$app->snowflake->id(),
                        'depart_id' => $id,
                        'parent_id' => $pid,
                        'del_time' => 0
                    ])
                    ->query();
            }

            $db->commitTrans();

            return true;

        } catch (\Exception $exception) {
            $db->rollBackTrans();
            throw $exception;
        }

    }
}