<?php
/**
 * File Name: Delete.php
 * Automatically generated by QHGC tool
 * @date: 2021-05-25 16:49:28
 * @version: 4.0.4
 */

namespace qh4module\rabc_adv\models\depart;


use qh4module\rabc_adv\external\ExtRabcAdv;
use QTTX;
use qttx\web\ServiceModel;

/**
 * Class Delete
 * 从tbl_bk_depart表的删除数据
 * @package backend\models\models\rabc
 * @property ExtRabcAdv $external
 */
class Delete extends ServiceModel
{
    /**
     * @var string[]|int[] 接收参数,必须：主键
     */
    public $ids;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['ids'],'required'],
            [['ids'], 'array', 'type' => function ($value) {
                return is_string($value) || is_numeric($value);
            }],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        $db = QTTX::$app->db;

        $db->beginTrans();

        try {

            $t = time();

            // 删除部门本身
            $db->update($this->external->departTableName())
                ->col('del_time', $t)
                ->whereIn('id',$this->ids)
                ->where('del_time=0')
                ->query();
            // 删除关联
            $db->update($this->external->departRelationTableName())
                ->col('del_time', $t)
                ->whereIn('depart_id', $this->ids)
                ->where('del_time=0')
                ->query();

            // 下级部门转为空上级
            $db->update($this->external->departRelationTableName())
                ->col('parent_id', '')
                ->whereIn('parent_id', $this->ids)
                ->where('del_time=0')
                ->query();

            // 删除用户管理


            $db->commitTrans();

            return true;

        } catch (\Exception $exception) {
            $db->rollBackTrans();
            
            throw $exception;
        }
    }
}
