<?php
/**
 * File Name: Detail.php
 * Automatically generated by QHGC tool
 * @date: 2021-05-25 16:49:28
 * @version: 4.0.4
 */

namespace qh4module\rabc_adv\models\depart;


use qh4module\rabc_adv\external\ExtRabcAdv;
use qh4module\rabc_adv\HpRabcAdv;
use qttx\web\ServiceModel;

/**
 * Class Detail
 * 获取tbl_bk_depart表的单条数据详细信息
 * @package backend\models\models\rabc
 * @property ExtRabcAdv $external
 */
class Detail extends ServiceModel
{
    /**
     * @var string|int 接收参数,必须：主键
     */
    public $id;
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [['id'],'required'],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        // 所有的字段,根据需要删减
        $fields = ['`ta`.`id`','`ta`.`name`','`ta`.`create_by`','`ta`.`create_time`',
            '`ta`.`desc`','`ta`.`del_time`'
        ];

        // 构建基础查询
        $tb_info = $this->external->userInfoTableName();
        $tb_depart = $this->external->departTableName();


        $result = $this->external->getDb()->select($fields)
            ->from("$tb_depart as ta")
            ->leftJoin("$tb_info as tb", 'ta.create_by=tb.user_id')
            ->whereArray(['id' => $this->id])
            ->row();

        if (empty($result)) {
            $this->addError('id', '部门不存在或已被删除');
            return false;
        }

        $result['parent_ids'] = HpRabcAdv::getDepartParent($this->id, [
            'id' => 'value',
            'name' => 'label',
        ], $this->external);

        return $result;
    }
}
